version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.2
  cli: circleci/circleci-cli@0.1.2

jobs:
  validate:
    executor: cli/default
    steps:
      - checkout
      - orb-tools/validate:
          orb-path: ./src/prettier.yml

workflows:
  test_and_publish:
    jobs:
      - validate
      - orb-tools/publish:
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
          requires:
            - validate
          orb-path: src/prettier.yml
          orb-ref: miyajan/prettier:${CIRCLE_TAG}
          publish-token-variable: ${ORB_PUBLISHING_TOKEN}
          validate: false
          checkout: true
