version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.2
  cli: circleci/circleci-cli@0.1.2

jobs:
  validate:
    executor: cli/default
    steps:
      - checkout
      - orb-tools/validate:
          orb-path: ./src/prettier.yml

workflows:
  pack_and_publish:
    jobs:
      - validate
